const products = [
  {
    id: 1,
    category: "Bathroom",
    name: "Sink",
    price: 300,
    image: "/assets/images/serenti35.jpg",
  },
  {
    id: 15,
    category: "Kitchen",
    name: "chair",
    price: 200,
    image: "/assets/images/pexels-pavel-danilyuk-7881483-removebg-preview.png",
  },
  {
    id: 16,
    category: "Bathroom",
    name: "Sink",
    price: 300,
    image: "/assets/images/pexels-pixabay-276534-removebg-preview.png",
  },
  {
    id: 17,
    category: "Bedroom",
    name: "Bed",
    price: 300,
    image: "/assets/images/pexels-max-vakhtbovych-6492400-removebg-preview.png",
  },
  {
    id: 18,
    category: "Bedroom",
    name: "Bed",
    price: 300,
    image: "/assets/images/pexels-max-vakhtbovych-7018391-removebg-preview.png",
  },
  // {
  //   id: 19,
  //   category: "Bathroom",
  //   name: "Sink",
  //   price: 300,
  //   image: "/assets/images/pexels-pavel-danilyuk-7881483-removebg-preview.png",
  // },
  {
    id: 20,
    category: "Bedroom",
    name: "Chair",
    price: 300,
    image: "/assets/images/pexels-pixabay-276534-removebg-preview.png",
  },
  {
    id: 21,
    category: "Bedroom",
    name: "couch",
    price: 300,
    image: "/assets/images/pexels-martin-péchy-1866149-removebg-preview.png",
  },
  {
    id: 2,
    category: "Kitchen",
    name: "Table",
    price: 6000,
    image: "/assets/images/serenti30.jpg",
  },
  {
    id: 3,
    category: "Balcony",
    name: "Sofa",
    price: 420,
    image: "/assets/images/serinti1.jpg",
  },
  {
    id: 4,
    category: "Bedroom",
    name: "Mirror",
    price: 300,
    image: "/assets/images/serinti2.jpg",
  },
  {
    id: 5,
    category: "Bathroom",
    name: "sink",
    price: 200,
    image: "/assets/images/serenti26.jpg",
  },
  {
    id: 6,
    category: "Bedroom",
    name: "Wardrobe",
    price: 500,
    image: "/assets/images/serinti11.jpg",
  },
  {
    id: 7,
    category: "Bedroom",
    name: "Table",
    price: 800,
    image: "/assets/images/serinti12.jpg",
  },
  {
    id: 8,
    category: "Bedroom",
    name: "Bed",
    price: 350,
    image: "/assets/images/serinti13.jpg",
  },
  {
    id: 9,
    category: "Office",
    name: "Chair",
    price: 2000,
    image: "/assets/images/serenti27.jpg",
  },
  {
    id: 10,
    category: "Bathroom",
    name: "sink",
    price: 1200,
    image: "/assets/images/serinti4.jpg",
  },
  {
    id: 11,
    category: "Kitchen",
    name: "sink",
    price: 1200,
    image: "/assets/images/photo-1582913130063-8318329a94a3.avif",
  },
  {
    id: 12,
    category: "Kitchen",
    name: "sink",
    price: 1200,
    image: "/assets/images/photo_6034830961490902259_y.jpg",
  },
  {
    id: 13,
    category: "Office",
    name: "sink",
    price: 1200,
    image: "/assets/images/photo-1592078615290-033ee584e267.avif",
  },
  {
    id: 14,
    category: "Kitchen",
    name: "sink",
    price: 1200,
    image: "/assets/images/photo-1600684388091-627109f3cd60.avif",
  },
  
  // {
  //   id: 16,
  //   category: "Kitchen",
  //   name: "chair",
  //   price: 200,
  //   image: "http://pngimg.com/uploads/vans/vans_PNG24.png",
  // },
];

export default products;
